
enum game_level
{
	零, 简单, 中等, 困难
};


//-----------------IMAGE------------------
#define IMG_BACKGROUND_WIDTH 600
#define IMG_BACKGROUND_HEIGHT 800


#define IMG_PLAYER_WIDTH 60
#define IMG_PLAYER_HEIGHT 60

#define IMG_GUNNER_WIDTH 6
#define IMG_GUNNER_HEIGHT 20

#define IMG_FOEBIG_WIDTH 150
#define IMG_FOEBIG_HEIGHT 100

#define IMG_FOEMIDDLE_WIDTH 80
#define IMG_FOEMIDDLE_HEIGHT 60

#define IMG_FOESMALL_WIDTH 60
#define IMG_FOESMALL_HEIGHT 40



//-----------------TIMER------------------
// 
// 
// 
//背景移动的定时器
#define TIMER_BACK_MOVE_ID	1
#define TIMER_BACK_MOVE_INTERVAL	100
#define TIMER_BACK_MOVE_STEP 3

#define TIMER_PLAYER_MOVE_ID	2
#define TIMER_PLAYER_MOVE_INTERVAL	20
#define TIMER_PLAYER_MOVE_STEP 3

#define TIMER_GUNNER_MOVE_ID	3
#define TIMER_GUNNER_MOVE_INTERVAL	4
#define TIMER_GUNNER_MOVE_STEP 8

#define TIMER_SEND_GUNNER_ID 4
#define TIMER_SEND_GUNNER_INTERVAL 500

#define TIMER_FOEBIG_MOVE_ID 5
#define TIMER_FOEBIG_MOVE_INTERVAL	10000

#define TIMER_FOEMIDDLE_MOVE_ID 6
#define TIMER_FOEMIDDLE_MOVE_INTERVAL	7000

#define TIMER_FOESMALL_MOVE_ID 7
#define TIMER_FOESMALL_MOVE_INTERVAL	4000

#define TIMER_FOE_MOVE_ID 8
#define TIMER_FOE_MOVE_INTERVAL	50

#define TIMER_FOEBIG_MOVE_STEP 3
#define TIMER_FOESMALL_MOVE_STEP 7
#define TIMER_FOEMIDDLE_MOVE_STEP 5


#define TIMER_HIT_ONE_ID	9
#define TIMER_HIT_ONE_INTERVAL	5

#define TIMER_CHANGE_PIG_ID 10
#define TIMER_CHANGE_PIG_INTERVAL 400


//----------------SETTING------------------

#define FOE_BIG_BLOOD(A) ((A)*(5))
#define FOE_SMALL_BLOOD(A) ((A)*(1))
#define FOE_MIDDLE_BLOOD(A) ((A)*(3))
#define GUNNER_DAMAGE(A) ((A)*(2))